//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSControlProje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMusteriler
    {
        public int musteriId { get; set; }
        public string musteriTc { get; set; }
        public string musteriAd { get; set; }
        public string musteriAdres { get; set; }
        public string musteriTelefon { get; set; }
        public int musteriPaket { get; set; }
    }
}
