//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSControlProje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblMusteriler
    {
        public int musteriId { get; set; }
        [Required]
        [StringLength(20)]
        public string musteriTc { get; set; }
        [Required]
        [StringLength(45)]
        public string musteriAd { get; set; }
        [Required]
        [StringLength(80)]
        public string musteriAdres { get; set; }
        [Required]
        [StringLength(15)]
        public string musteriTelefon { get; set; }
        [Required]
        public int musteriPaket { get; set; }
    }
}
