//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSControlProje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class tblPaketler
    {
        public int paketId { get; set; }
        [Required]
        [StringLength(55)]
        public string paketAd { get; set; }
        [Required]
        [StringLength(10)]
        public string paketFiyat { get; set; }
        [AllowHtml]
        [Required]
        public string paketAciklamasi { get; set; }
    }
}
