//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSControlProje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPaketler
    {
        public int paketId { get; set; }
        public string paketAd { get; set; }
        public string paketFiyat { get; set; }
        public string paketAciklamasi { get; set; }
    }
}
