//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSControlProje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSatis
    {
        public int satisId { get; set; }
        public Nullable<int> paket { get; set; }
        public Nullable<int> musteri { get; set; }
        public string taahut { get; set; }
    
        public virtual tblMusteriler tblMusteriler { get; set; }
        public virtual tblPaketler tblPaketler { get; set; }
    }
}
